# Generated by Django 3.0.3 on 2020-02-15 16:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='slug')),
            ],
        ),
    ]
